// Mock Data reflecting DermAI / TeleDerma Prototype and Requirements

export const mockPatient = {
  id: 'pat-001',
  name: 'Patient User',
  age: 28,
  gender: 'Male',
  phone: '+91 98765 43210',
  email: 'patient@example.com',
  bloodGroup: 'B+',
  city: 'Mumbai',
  allergies: ['Penicillin', 'Sulfa Drugs'],
  existingConditions: ['Asthma (mild)'],
  currentMedications: ['Cetirizine 10mg (PRN)'],
  previousSkinProblems: ['Acne Vulgaris in teens', 'Contact dermatitis'],
  skinType: 'Combination / Oily T-zone',
  fitzpatrickScale: 'Type IV (Moderate Brown)',
  avatarText: 'P',
};

export const mockDoctors = [
  {
    id: 'doc-001',
    name: 'Dr. Priya Sundaram',
    qualification: 'MBBS, MD (Dermatology, AIIMS)',
    specialization: 'Clinical & Cosmetic Dermatology',
    experience: 14,
    rating: 4.9,
    reviewsCount: 380,
    fee: 800,
    verified: true,
    availableToday: true,
    about: 'Senior Consultant Dermatologist with 14+ years of clinical experience specializing in acneiform eruptions, eczema, and dermato-surgery.',
    languages: ['English', 'Hindi', 'Tamil'],
    hospital: 'Apex Skin & Laser Institute, Mumbai',
    availableDates: ['Today', 'Tomorrow', 'Oct 04', 'Oct 05'],
    slots: [
      { id: 's1', time: '09:30 AM', available: true },
      { id: 's2', time: '10:00 AM', available: false },
      { id: 's3', time: '11:15 AM', available: true },
      { id: 's4', time: '02:30 PM', available: true },
      { id: 's5', time: '04:00 PM', available: true },
      { id: 's6', time: '05:30 PM', available: false },
    ],
  },
  {
    id: 'doc-002',
    name: 'Dr. Ananya Sharma',
    qualification: 'MBBS, DNB, DVD (Gold Medalist)',
    specialization: 'Pediatric Dermatology & Allergy',
    experience: 10,
    rating: 4.8,
    reviewsCount: 295,
    fee: 700,
    verified: true,
    availableToday: true,
    about: 'Specialist in sensitive skin syndromes, psoriasis, and pediatric skin conditions. Emphasizes holistic barrier repair treatments.',
    languages: ['English', 'Hindi', 'Marathi'],
    hospital: 'DermaCare Specialty Clinic',
    availableDates: ['Today', 'Tomorrow', 'Oct 06'],
    slots: [
      { id: 's21', time: '10:30 AM', available: true },
      { id: 's22', time: '11:45 AM', available: true },
      { id: 's23', time: '03:15 PM', available: true },
      { id: 's24', time: '06:00 PM', available: true },
    ],
  },
  {
    id: 'doc-003',
    name: 'Dr. Rohan Mehta',
    qualification: 'MBBS, MD (Skin & VD)',
    specialization: 'Trichology & Scalp Disorders',
    experience: 8,
    rating: 4.7,
    reviewsCount: 210,
    fee: 600,
    verified: true,
    availableToday: false,
    about: 'Expert in scalp disorders, alopecia areata, fungal infections, and hyperpigmentation therapy.',
    languages: ['English', 'Hindi', 'Gujarati'],
    hospital: 'Metro Skin Hospital',
    availableDates: ['Tomorrow', 'Oct 05', 'Oct 07'],
    slots: [
      { id: 's31', time: '11:00 AM', available: true },
      { id: 's32', time: '01:30 PM', available: true },
      { id: 's33', time: '04:45 PM', available: true },
    ],
  },
  {
    id: 'doc-004',
    name: 'Dr. Vikram Singh',
    qualification: 'MBBS, MD, Fellowship in Dermato-Oncology',
    specialization: 'Dermatopathology & Mole Analysis',
    experience: 16,
    rating: 4.95,
    reviewsCount: 512,
    fee: 1000,
    verified: true,
    availableToday: true,
    about: 'Specialized in atypical mole monitoring, skin cancer screenings, and complex inflammatory skin diseases.',
    languages: ['English', 'Hindi', 'Punjabi'],
    hospital: 'National Derma Center',
    availableDates: ['Today', 'Tomorrow'],
    slots: [
      { id: 's41', time: '02:00 PM', available: true },
      { id: 's42', time: '03:30 PM', available: true },
      { id: 's43', time: '05:00 PM', available: true },
    ],
  },
];

export const mockAppointments = [
  {
    id: 'appt-101',
    doctorId: 'doc-001',
    doctorName: 'Dr. Priya Sundaram',
    doctorSpecialization: 'Clinical & Cosmetic Dermatology',
    date: '2026-10-02',
    time: '09:30 AM',
    status: 'CONFIRMED',
    type: 'Video Consultation',
    fee: 800,
    paid: true,
    symptoms: ['Pustular acne on cheek', 'Moderate itching'],
    triageLevel: 'YELLOW',
    meetRoomId: 'td-room-8821',
  },
  {
    id: 'appt-102',
    doctorId: 'doc-002',
    doctorName: 'Dr. Ananya Sharma',
    doctorSpecialization: 'Pediatric Dermatology & Allergy',
    date: '2026-09-15',
    time: '11:30 AM',
    status: 'COMPLETED',
    type: 'Video Consultation',
    fee: 700,
    paid: true,
    symptoms: ['Mild redness', 'Dry patches on forearm'],
    triageLevel: 'GREEN',
    meetRoomId: 'td-room-7712',
    hasPrescription: true,
  },
];

export const mockPrescriptions = [
  {
    id: 'rx-201',
    doctorName: 'Dr. Priya Sundaram',
    date: '2026-09-15',
    diagnosis: 'Acne Vulgaris with Secondary Erythema',
    activeIngredient: 'Adapalene + Clindamycin',
    medicines: [
      {
        name: 'Adapalene Gel 0.1%',
        dosage: 'Pea-sized quantity',
        frequency: 'Once daily at bedtime',
        duration: '4 Weeks',
        instructions: 'Apply gently after washing face with mild cleanser. Avoid direct sunlight. Use broad-spectrum sunscreen in daytime.',
      },
      {
        name: 'Clindamycin Phosphate Gel 1%',
        dosage: 'Thin layer',
        frequency: 'Twice daily (Morning & Evening)',
        duration: '2 Weeks',
        instructions: 'Apply to active inflammatory lesions only.',
      },
      {
        name: 'Hydrating Ceramide Barrier Cream',
        dosage: 'Generous amount',
        frequency: 'Twice daily or as needed',
        duration: 'Continuous',
        instructions: 'Apply 10 minutes after medicated gel to restore barrier moisture.',
      },
    ],
    notes: 'Schedule a follow-up consultation in 14 days with updated progress photo. Avoid physical scrubs or peeling agents.',
    followUpDate: '2026-10-15',
  },
];

export const mockMedicineCatalog = [
  {
    id: 'med-1',
    activeIngredient: 'Adapalene (0.1%)',
    category: 'Topical Retinoid',
    indication: 'Acne vulgaris, comedones, follicular keratosis',
    prescriptionRequired: true,
    description: 'Third-generation synthetic retinoid that modulates cellular differentiation and keratinization.',
    dosageForm: 'Gel',
    strength: '0.1%',
    brands: [
      { id: 'b-5', name: 'Adiff Gel 0.1% (Sun Pharma)', manufacturer: 'Sun Pharma', price: 185, size: '15g Tube', form: 'Gel', prescriptionRequired: true },
      { id: 'b-4', name: 'Acfree Gel (Cipla)', manufacturer: 'Cipla', price: 210, size: '15g Tube', form: 'Gel', prescriptionRequired: true },
      { id: 'b-2', name: 'Deriva-CMS Gel (Glenmark)', manufacturer: 'Glenmark', price: 295, size: '15g Tube', form: 'Gel', prescriptionRequired: true },
      { id: 'b-1', name: 'Adaferin Gel 0.1% (Galderma)', manufacturer: 'Galderma', price: 345, size: '15g Tube', form: 'Gel', prescriptionRequired: true },
      { id: 'b-3', name: 'Differin 0.1% (Galderma)', manufacturer: 'Galderma', price: 420, size: '30g Tube', form: 'Cream', prescriptionRequired: true },
    ],
  },
  {
    id: 'med-2',
    activeIngredient: 'Clindamycin Phosphate (1%)',
    category: 'Topical Lincosamide Antibiotic',
    indication: 'Inflammatory acne, bacterial folliculitis',
    prescriptionRequired: true,
    description: 'Bacteriostatic agent that inhibits bacterial protein synthesis of Propionibacterium acnes.',
    dosageForm: 'Gel',
    strength: '1%',
    brands: [
      { id: 'b-9', name: 'Clincin Gel 1% (Torrent Pharma)', manufacturer: 'Torrent Pharma', price: 140, size: '20g Tube', form: 'Gel', prescriptionRequired: true },
      { id: 'b-6', name: 'Clindac-A Gel (Alkem)', manufacturer: 'Alkem Laboratories', price: 165, size: '20g Tube', form: 'Gel', prescriptionRequired: true },
      { id: 'b-8', name: 'Cleargel 1% (Curatio)', manufacturer: 'Curatio Healthcare', price: 172, size: '15g Tube', form: 'Gel', prescriptionRequired: true },
      { id: 'b-7', name: 'Erytop Gel 1% (USV Ltd)', manufacturer: 'USV Ltd', price: 185, size: '20g Tube', form: 'Gel', prescriptionRequired: true },
    ],
  },
  {
    id: 'med-3',
    activeIngredient: 'Ketoconazole (2%)',
    category: 'Antifungal',
    indication: 'Seborrheic dermatitis, tinea versicolor, dandruff',
    prescriptionRequired: false,
    description: 'Broad-spectrum synthetic imidazole antifungal agent that inhibits ergosterol synthesis.',
    dosageForm: 'Lotion / Shampoo',
    strength: '2%',
    brands: [
      { id: 'b-12', name: 'Keto Soap 2% (Med Manor)', manufacturer: 'Med Manor Organics', price: 120, size: '75g Bar', form: 'Soap', prescriptionRequired: false },
      { id: 'b-13', name: 'Ketofly Shampoo 2% (Leeford)', manufacturer: 'Leeford Healthcare', price: 160, size: '100ml', form: 'Shampoo', prescriptionRequired: false },
      { id: 'b-11', name: 'Scalpe Pro Anti-Dandruff (Glenmark)', manufacturer: 'Glenmark', price: 275, size: '100ml', form: 'Shampoo', prescriptionRequired: false },
      { id: 'b-10', name: 'Nizral 2% Shampoo (Janssen)', manufacturer: 'Janssen / J&J', price: 380, size: '100ml', form: 'Lotion / Shampoo', prescriptionRequired: false },
    ],
  },
  {
    id: 'med-4',
    activeIngredient: 'Hydrocortisone (1%)',
    category: 'Mild Topical Corticosteroid',
    indication: 'Eczema, contact dermatitis, insect bites',
    prescriptionRequired: true,
    description: 'Mild potency topical corticosteroid for reducing inflammatory redness and itching.',
    dosageForm: 'Cream',
    strength: '1%',
    brands: [
      { id: 'b-14', name: 'Hicort 1% Cream (Ranbaxy)', manufacturer: 'Ranbaxy / Sun Pharma', price: 85, size: '10g Tube', form: 'Cream', prescriptionRequired: true },
      { id: 'b-16', name: 'Cortizone-10 (Chattem)', manufacturer: 'Chattem Inc.', price: 180, size: '28g Tube', form: 'Cream', prescriptionRequired: true },
      { id: 'b-15', name: 'Locoid Lipo Cream (Leo Pharma)', manufacturer: 'Leo Pharma', price: 195, size: '30g Tube', form: 'Cream', prescriptionRequired: true },
    ],
  },
  {
    id: 'med-5',
    activeIngredient: 'Niacinamide (5% - 10%) + Zinc PCA',
    category: 'Barrier Repair & Sebum Regulator',
    indication: 'Blemishes, enlarged pores, redness, hyperpigmentation',
    prescriptionRequired: false,
    description: 'Vitamin B3 derivative that strengthens epidermal lipid synthesis and soothes inflammation.',
    dosageForm: 'Serum',
    strength: '10% + 1%',
    brands: [
      { id: 'b-20', name: 'Derma Co 10% Niacinamide Serum', manufacturer: 'Honer Consumer Products', price: 499, size: '30ml', form: 'Serum', prescriptionRequired: false },
      { id: 'b-19', name: 'Plum 10% Niacinamide Rice Water', manufacturer: 'Pureplay Skin Sciences', price: 520, size: '30ml', form: 'Serum', prescriptionRequired: false },
      { id: 'b-17', name: 'Minimalist 10% Niacinamide Serum', manufacturer: 'Uprising Science', price: 599, size: '30ml', form: 'Serum', prescriptionRequired: false },
      { id: 'b-18', name: 'The Ordinary Niacinamide 10% + Zinc 1%', manufacturer: 'Deciem', price: 600, size: '30ml', form: 'Serum', prescriptionRequired: false },
    ],
  },
  {
    id: 'med-6',
    activeIngredient: 'Benzoyl Peroxide (2.5% - 5%)',
    category: 'Topical Antibacterial & Keratolytic',
    indication: 'Inflammatory acne lesions, papules, pustules',
    prescriptionRequired: false,
    description: 'Generates free radical oxygen species that eliminate P. acnes bacteria and unplug follicles.',
    dosageForm: 'Gel / Wash',
    strength: '2.5% - 5%',
    brands: [
      { id: 'b-24', name: 'Benxop 2.5% Gel (Apex Labs)', manufacturer: 'Apex Laboratories', price: 125, size: '20g Tube', form: 'Gel', prescriptionRequired: false },
      { id: 'b-23', name: 'Pernex AC 5% Gel (Cosme Farma)', manufacturer: 'Cosme Farma', price: 140, size: '20g Tube', form: 'Gel', prescriptionRequired: false },
      { id: 'b-21', name: 'Benzac AC 2.5% Gel (Galderma)', manufacturer: 'Galderma', price: 175, size: '30g Tube', form: 'Gel', prescriptionRequired: false },
      { id: 'b-22', name: 'Brevoxyl 4% Creamy Wash (GSK)', manufacturer: 'GlaxoSmithKline', price: 230, size: '50g Tube', form: 'Cream', prescriptionRequired: false },
    ],
  },
  {
    id: 'med-7',
    activeIngredient: 'Salicylic Acid (2%)',
    category: 'Beta Hydroxy Acid (BHA) Exfoliant',
    indication: 'Blackheads, whiteheads, excess oil, rough skin texture',
    prescriptionRequired: false,
    description: 'Lipid-soluble chemical exfoliant that penetrates deep into pores to dissolve sebum build-up.',
    dosageForm: 'Gel / Face Wash',
    strength: '2%',
    brands: [
      { id: 'b-28', name: "Salicylix SF 6% Ointment (Dr. Reddy's)", manufacturer: "Dr. Reddy's", price: 135, size: '50g Tube', form: 'Ointment', prescriptionRequired: false },
      { id: 'b-25', name: 'Sebogel 2% (Cipla)', manufacturer: 'Cipla', price: 280, size: '30g Tube', form: 'Gel', prescriptionRequired: false },
      { id: 'b-26', name: 'Saslic DS Face Wash (Cipla)', manufacturer: 'Cipla', price: 395, size: '60ml', form: 'Foam Wash', prescriptionRequired: false },
      { id: 'b-27', name: 'Minimalist 2% Salicylic Acid Serum', manufacturer: 'Uprising Science', price: 549, size: '30ml', form: 'Serum', prescriptionRequired: false },
    ],
  },
  {
    id: 'med-8',
    activeIngredient: 'Tretinoin (0.025% - 0.05%)',
    category: 'First-Generation Retinoid',
    indication: 'Comedonal acne, photoaging, coarse skin wrinkling',
    prescriptionRequired: true,
    description: 'Potent vitamin A metabolite that stimulates cellular epidermal turnover and collagen production.',
    dosageForm: 'Cream / Gel',
    strength: '0.025% - 0.05%',
    brands: [
      { id: 'b-31', name: 'Tretiheal 0.05% Cream (Healing Pharma)', manufacturer: 'Healing Pharma', price: 160, size: '20g Tube', form: 'Cream', prescriptionRequired: true },
      { id: 'b-30', name: 'A-Ret 0.05% Gel (Menarini)', manufacturer: 'Menarini India', price: 195, size: '20g Tube', form: 'Gel', prescriptionRequired: true },
      { id: 'b-29', name: 'Retino-A 0.025% Cream (Janssen)', manufacturer: 'Janssen / J&J', price: 215, size: '20g Tube', form: 'Cream', prescriptionRequired: true },
    ],
  },
  {
    id: 'med-9',
    activeIngredient: 'Azelaic Acid (10% - 20%)',
    category: 'Dicarboxylic Acid Anti-inflammatory',
    indication: 'Rosacea, post-inflammatory erythema (PIE), melasma',
    prescriptionRequired: true,
    description: 'Competitively inhibits tyrosinase to diminish hyperpigmentation and calms vascular facial redness.',
    dosageForm: 'Gel / Cream',
    strength: '10% - 20%',
    brands: [
      { id: 'b-32', name: 'Aziderm 10% Gel (Micro Labs)', manufacturer: 'Micro Labs', price: 270, size: '15g Tube', form: 'Gel', prescriptionRequired: true },
      { id: 'b-34', name: 'Exazel-N Cream (Cosme Farma)', manufacturer: 'Cosme Farma', price: 310, size: '20g Tube', form: 'Cream', prescriptionRequired: true },
      { id: 'b-33', name: 'Picspot 20% Gel (Curatio)', manufacturer: 'Curatio Healthcare', price: 340, size: '15g Tube', form: 'Gel', prescriptionRequired: true },
      { id: 'b-35', name: 'Aziderm 20% Cream (Micro Labs)', manufacturer: 'Micro Labs', price: 380, size: '15g Tube', form: 'Cream', prescriptionRequired: true },
    ],
  },
  {
    id: 'med-10',
    activeIngredient: 'Ceramide Complex (1% - 3%)',
    category: 'Epidermal Barrier Restorer',
    indication: 'Compromised skin barrier, atopic eczema, flaking dryness',
    prescriptionRequired: false,
    description: 'Multi-ceramide physiological lipid complex that mimics the natural stratum corneum lipid matrix.',
    dosageForm: 'Cream / Lotion',
    strength: '1% - 3%',
    brands: [
      { id: 'b-39', name: 'Venusia Max Intensive Cream', manufacturer: "Dr. Reddy's", price: 320, size: '150g Jar', form: 'Cream', prescriptionRequired: false },
      { id: 'b-37', name: 'Cetaphil DAM Daily Advanced Ultra', manufacturer: 'Galderma', price: 395, size: '30g Tube', form: 'Lotion', prescriptionRequired: false },
      { id: 'b-36', name: 'Cerave Moisturizing Cream', manufacturer: "L'Oreal / CeraVe", price: 450, size: '50g Tube', form: 'Cream', prescriptionRequired: false },
      { id: 'b-38', name: 'Bioderma Atoderm Intensive Baume', manufacturer: 'NAOS Bioderma', price: 799, size: '75ml', form: 'Baume', prescriptionRequired: false },
    ],
  },
  {
    id: 'med-11',
    activeIngredient: 'Clotrimazole (1%)',
    category: 'Topical Antifungal',
    indication: "Ringworm (Tinea corporis), athlete's foot, jock itch",
    prescriptionRequired: false,
    description: 'Broad-spectrum imidazole antifungal that inhibits fungal cell wall ergosterol biosynthesis.',
    dosageForm: 'Cream',
    strength: '1%',
    brands: [
      { id: 'b-42', name: 'Clocip Cream 1% (Cipla)', manufacturer: 'Cipla', price: 85, size: '20g Tube', form: 'Cream', prescriptionRequired: false },
      { id: 'b-40', name: 'Candid Cream 1% (Glenmark)', manufacturer: 'Glenmark', price: 110, size: '30g Tube', form: 'Cream', prescriptionRequired: false },
      { id: 'b-41', name: 'Canesten 1% Cream (Bayer)', manufacturer: 'Bayer Pharmaceuticals', price: 135, size: '30g Tube', form: 'Cream', prescriptionRequired: false },
    ],
  },
];

export const mockTreatmentTimeline = [
  {
    day: 'Day 1',
    date: '2026-09-01',
    stage: 'Initial Skin Photo',
    status: 'Baseline Assessment',
    finding: 'Active inflammatory pustules with diffuse erythema across right cheek.',
    triage: 'YELLOW',
    notes: 'Prescription initiated: Adapalene + Clindamycin.',
  },
  {
    day: 'Day 7',
    date: '2026-09-08',
    stage: 'Week 1 Progress',
    status: 'Follow-up Check',
    finding: 'Mild peeling observed, initial purging settling, redness reduced by 25%.',
    triage: 'YELLOW',
    notes: 'Patient advised to increase moisturizer application frequency.',
  },
  {
    day: 'Day 14',
    date: '2026-09-15',
    stage: 'Week 2 Progress',
    status: 'Mid-term Review',
    finding: 'Active lesions significantly decreased. Post-inflammatory marks visible.',
    triage: 'GREEN',
    notes: 'Continued regimen. No new flare-ups recorded.',
  },
  {
    day: 'Day 30',
    date: '2026-09-30',
    stage: 'Month 1 Check-in',
    status: 'Maintenance Stage',
    finding: 'Clear skin achieved. Residual hyperpigmentation undergoing normal turnover.',
    triage: 'GREEN',
    notes: 'Ready for maintenance sunscreen + gentle barrier repair protocol.',
  },
];

export const mockReminders = [
  {
    id: 'rem-1',
    title: 'Apply Adapalene Gel 0.1%',
    subtitle: 'Bedtime medicine reminder',
    time: '10:00 PM',
    type: 'MEDICINE',
    frequency: 'Daily',
    active: true,
  },
  {
    id: 'rem-2',
    title: 'Upload Follow-up Progress Photo',
    subtitle: 'Dr. Priya Sundaram requested 14-day check-in photo',
    time: 'Due Oct 05, 2026',
    type: 'PROGRESS_PHOTO',
    frequency: 'One-time',
    active: true,
  },
  {
    id: 'rem-3',
    title: 'Consultation with Dr. Priya Sundaram',
    subtitle: 'Video call starting at 09:30 AM',
    time: 'Today, 09:30 AM',
    type: 'APPOINTMENT',
    frequency: 'One-time',
    active: true,
  },
];
